export const appTypes = {
  FETCH_USERS: 'FETCH_USERS',
  FETCH_FEED: 'FETCH_FEED',
  PRESS_LIKE: 'PRESS_LIKE',
  PRESS_DISLIKE: 'PRESS_DISLIKE',
  FOLLOW: 'FOLLOW',
  UNFOLLOW: 'UNFOLLOW',
  CLEAR_DATA: 'CLEAR_DATA',
}
